# HGMAE 

1. install module
2. model training
3. final embedding

## Install Module

In [5]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())


2.1.0+cu121
12.1
True


In [18]:
!pip uninstall -y torch torchvision torchaudio torchdata dgl

Found existing installation: torch 2.1.0+cu121
Uninstalling torch-2.1.0+cu121:
  Successfully uninstalled torch-2.1.0+cu121
Found existing installation: torchvision 0.16.0+cu121
Uninstalling torchvision-0.16.0+cu121:
  Successfully uninstalled torchvision-0.16.0+cu121
Found existing installation: torchaudio 2.1.0+cu121
Uninstalling torchaudio-2.1.0+cu121:
  Successfully uninstalled torchaudio-2.1.0+cu121
Found existing installation: torchdata 0.7.0
Uninstalling torchdata-0.7.0:
  Successfully uninstalled torchdata-0.7.0
Found existing installation: dgl 2.1.0+cu121
Uninstalling dgl-2.1.0+cu121:
  Successfully uninstalled dgl-2.1.0+cu121


In [1]:
# PyTorch 2.1.0 + CUDA 12.1
!pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0+cu121 --index-url https://download.pytorch.org/whl/cu121

# TorchData 맞춤
!pip install torchdata==0.7.0

# DGL with GraphBolt (CUDA 12.1)
!pip install dgl -f https://data.dgl.ai/wheels/cu121/repo.html

Looking in indexes: https://download.pytorch.org/whl/cu121
Looking in links: https://data.dgl.ai/wheels/cu121/repo.html
  Using cached https://data.dgl.ai/wheels/cu121/dgl-2.1.0%2Bcu121-cp310-cp310-manylinux1_x86_64.whl (467.5 MB)


In [2]:
# 설치 확인 

import torch, torchvision, torchaudio, torchdata, dgl
import dgl.graphbolt as gb

print("Torch:", torch.__version__)
print("TorchData:", torchdata.__version__)
print("Torchvision:", torchvision.__version__)
print("Torchaudio:", torchaudio.__version__)
print("DGL:", dgl.__version__)
print("CUDA:", torch.version.cuda)
print("GPU available:", torch.cuda.is_available())


Torch: 2.1.0+cu121
TorchData: 0.7.0
Torchvision: 0.16.0+cu121
Torchaudio: 2.1.0+cu121
DGL: 2.1.0+cu121
CUDA: 12.1
GPU available: True


In [3]:
# warning message 끄기
!pip install pickleshare --root-user-action=ignore

In [4]:
!pip install tqdm

## Model Training

In [1]:
import torch, torchvision, torchaudio, torchdata, dgl
import dgl.graphbolt as gb

In [2]:
%cd /root/HGMAE

/root/HGMAE


In [3]:
import torch
data = torch.load("data/mydata.pkl")

import torch
data = torch.load("data/mydata.pkl")
print("keys in mydata.pkl:", data.keys())


keys in mydata.pkl: dict_keys(['feats', 'mps', 'nei_index', 'pos'])


In [4]:
import torch
data = torch.load("data/mydata.pkl")

for k in data["feats"]:
    print(k, data["feats"][k].shape)

# paper torch.Size([5000, 832])
# author torch.Size([33607, 768])
# concept torch.Size([6612, 768])

paper torch.Size([5000, 832])
author torch.Size([33607, 768])
concept torch.Size([6612, 768])


In [6]:
for name, edge_index in data["pos"].items():
    print(name, edge_index.shape)

ap torch.Size([2, 40758])
pc torch.Size([2, 82238])
pp torch.Size([2, 8186])
aa torch.Size([2, 984700])


In [7]:
for name, mat in data["mps"].items():
    print(name, mat.shape)


PAP torch.Size([33607, 33607])
PCP torch.Size([5000, 5000])


In [1]:
%cd /root/HGMAE
!python main.py --dataset mydata --task contrastive --use_cfg --epochs 150

/root/HGMAE
------ Use best configs ------
Namespace(seeds=[0], num_heads=4, num_out_heads=1, num_layers=1, residual=True, feat_drop=0.2, attn_drop=0.2, norm='layernorm', lr=0.001, negative_slope=0.2, activation='prelu', feat_mask_rate='0.3,0.05,0.25', replace_rate=0.1, leave_unchanged=0.1, encoder='han', decoder='han', loss_fn='sce', alpha_l=2, optimizer='adam', scheduler='cosine', scheduler_gamma=0.99, dataset='mydata', ratio=[20, 40, 60], gpu=0, seed=0, hidden_dim=512, mae_epochs=50, eva_lr=0.05, eva_wd=0.0, patience=10, l2_coef=0.0005, use_mp2vec_feat_pred=False, mps_lr=0.005, mps_embedding_dim=64, mps_walk_length=5, mps_context_size=3, mps_walks_per_node=3, mps_num_negative_samples=1, mps_batch_size=128, mps_epoch=50, mp2vec_feat_pred_loss_weight=0.1, mp2vec_feat_alpha_l=2, mp2vec_feat_drop=0.2, use_cfg=True, use_mp_edge_recon=False, mp_edge_recon_loss_weight=1, mp_edge_mask_rate=0.3, mp_edge_alpha_l=2, task='contrastive', contrastive_weight=1.0, mae_weight=1.0, tau=0.5, hard_neg_

## Final Embedding 

In [2]:
import numpy as np

# 파일 경로
path = "/root/HGMAE/embeddings.npy"

# 불러오기
embeddings = np.load(path)

print("Shape:", embeddings.shape)
print("Dtype:", embeddings.dtype)

# 앞 5개 행 출력
print("First 5 embeddings:\n", embeddings[:10])


Shape: (5000, 512)
Dtype: float32
First 5 embeddings:
 [[0.24876194 0.14389117 0.46494567 ... 0.2660499  0.17222154 0.05553541]
 [0.17449698 0.13445519 0.5479781  ... 0.26801953 0.34459224 0.29198402]
 [0.28962123 0.22092982 0.36324188 ... 0.05182059 0.1699028  0.12909499]
 ...
 [0.2193987  0.01143015 0.44400483 ... 0.28498003 0.03462566 0.22011498]
 [0.24123284 0.37747315 0.24810821 ... 0.15827772 0.17780797 0.1730656 ]
 [0.3867326  0.03622517 0.37573007 ... 0.34329483 0.28516996 0.13198513]]


In [3]:
# sanity check

import pandas as pd
import numpy as np

embeddings = np.load("/root/HGMAE/embeddings.npy")
meta_df = pd.read_csv("/root/cs_data.csv")

print("임베딩 행 수:", embeddings.shape[0])
print("cs_data 행 수:", len(meta_df))

# paper_id 앞 5개 출력
print(meta_df["paper_id"].head())

# 임베딩 앞 1개 벡터 길이 확인
print("첫 번째 임베딩 벡터:", embeddings[0][:10])  # 앞 10차원만 보기


임베딩 행 수: 5000
cs_data 행 수: 5000
0    https://openalex.org/W3010906965
1    https://openalex.org/W4213446860
2    https://openalex.org/W2987460522
3    https://openalex.org/W3133928066
4    https://openalex.org/W4382464460
Name: paper_id, dtype: object
첫 번째 임베딩 벡터: [ 0.24876194  0.14389117  0.46494567 -0.01029712  0.07939439  0.08515264
  0.5616668   0.09866195 -0.23705757  0.18434714]


In [4]:
# paper_id 컬럼 맨앞에 붙여서 다시 저장 

embeddings = np.load("/root/HGMAE/embeddings.npy")
meta_df = pd.read_csv("/root/cs_data.csv")

df = pd.DataFrame(embeddings)
df.insert(0, "paper_id", meta_df["paper_id"].values)

OUT_PATH = "/root/HGMAE/hgmae_embeddings_with_paperid.csv"
df.to_csv(OUT_PATH, index=False)

print("Saved:", OUT_PATH, "shape:", df.shape)



Saved: /root/HGMAE/hgmae_embeddings_with_paperid.csv shape: (5000, 513)


## Pos/Neg pair split 잘 됐는지 확인 

In [21]:
%cd /root/HGMAE
import torch
import pickle

# 파일 로드
with open("pairs_debug.pkl", "rb") as f:
    pairs = pickle.load(f)

print("Top-level keys:", pairs.keys())
print("Subkeys (pos):", pairs["pos"].keys())
print("Subkeys (neg):", pairs["neg"].keys())

def check_edges(edges, name, num_nodes=None):
    print(f"\n=== {name.upper()} ===")
    if edges is None or len(edges) == 0:
        print("⚠️ 없음")
        return None
    
    if isinstance(edges, torch.Tensor):
        e = edges.clone().cpu()
        if e.ndim == 2 and e.shape[0] == 2:
            e = e.t()
    else:
        e = torch.as_tensor(edges, dtype=torch.long)
        if e.ndim == 2 and e.shape[0] == 2:
            e = e.t()
    
    print(f"총 개수: {e.shape[0]}")
    
    uniq = torch.unique(e, dim=0)
    print(f"중복 제거 후 개수: {uniq.shape[0]} (중복 {e.shape[0] - uniq.shape[0]})")
    
    if num_nodes:
        invalid = ((e < 0) | (e >= num_nodes)).any(dim=1).sum().item()
        print(f"유효하지 않은 노드 index 개수: {invalid}")
    
    return e

# 예시: paper 타입만 확인
pos_paper = pairs["pos"]["train"].get("paper")
neg_paper = pairs["neg"]["train"].get("paper")

pos_e = check_edges(pos_paper, "pos_train[paper]", num_nodes=5000)
neg_e = check_edges(neg_paper, "neg_train[paper]", num_nodes=5000)

# pos-neg 교집합
if pos_e is not None and neg_e is not None:
    inter = set(map(tuple, pos_e.tolist())) & set(map(tuple, neg_e.tolist()))
    print(f"\nPos-Neg 교집합 개수: {len(inter)}")
    if len(inter) > 0:
        print("예시 교집합:", list(inter)[:10])


/root/HGMAE
Top-level keys: dict_keys(['pos', 'neg'])
Subkeys (pos): dict_keys(['train', 'val'])
Subkeys (neg): dict_keys(['train', 'val'])

=== POS_TRAIN[PAPER] ===
총 개수: 6823
중복 제거 후 개수: 6823 (중복 0)
유효하지 않은 노드 index 개수: 0

=== NEG_TRAIN[PAPER] ===
총 개수: 6822
중복 제거 후 개수: 6822 (중복 0)
유효하지 않은 노드 index 개수: 0

Pos-Neg 교집합 개수: 0


In [22]:
%cd /root/HGMAE
import torch

data = torch.load("data/mydata.pkl", map_location="cpu")  # GPU → CPU 로드
print("Keys in mydata.pkl:", data.keys())

if "pos" in data:
    pos = data["pos"]
    print("Type of pos:", type(pos))
    if isinstance(pos, dict):
        for k, v in pos.items():
            print(f"{k}: shape={getattr(v, 'shape', None)} type={type(v)}")
    else:
        print("pos content:", pos)



/root/HGMAE
Keys in mydata.pkl: dict_keys(['feats', 'mps', 'nei_index', 'pos'])
Type of pos: <class 'dict'>
ap: shape=torch.Size([2, 40758]) type=<class 'torch.Tensor'>
pc: shape=torch.Size([2, 82238]) type=<class 'torch.Tensor'>
pp: shape=torch.Size([2, 8186]) type=<class 'torch.Tensor'>
aa: shape=torch.Size([2, 984700]) type=<class 'torch.Tensor'>


## Tuning 

In [ ]:
%cd /root/HGMAE
!python main.py --dataset mydata --task contrastive --use_cfg --epochs 50

In [ ]:
%cd /root/HGMAE
!python main.py --dataset mydata --task contrastive --use_cfg --epochs 100

In [ ]:
%cd /root/HGMAE
!python main.py --dataset mydata --task contrastive --use_cfg --epochs 150